### PR TITLE
suggestion demo

### PR DESCRIPTION
**Pull request by choper725**
suggetsion demo filter contain insted of starts with

### CODE REVIEW

**Comment by choper725** [comment]
@oblomov-dev 

not really sure what those errors are, i changed demo 2 and 60 only

**Comment by oblomov-dev** [comment]
Mhh it runs very Long, can't see on my phone what is wrong but will check it later

**Comment by choper725** [comment]
> Mhh it runs very Long, can't see on my phone what is wrong but will check it later

method rtti_get_t_attri_by_struc not found .. and according paramerts in 3 demos..

**Comment by oblomov-dev** [comment]
Ah changed the name of the method today, did you pull the sample correctly? It's called rtti_get_t_attri_by_any now.

**Comment by choper725** [comment]
yes i pulled correctly and latest..

**Comment by oblomov-dev** [comment]
forget to merge my latest changes, now both PRs are merged and it should work

**Pull request merged**
