### PR TITLE
 feed input, variant managment (wip), view settings 

### PR DESCRIPTION
**Pull request by choper725**
feed input, variant managment (wip), view settings dialog

### CODE REVIEW

**Comment by oblomov-dev** [comment]
thank you

**Comment by oblomov-dev** [comment]
Looks great:
image
image

**Comment by choper725** [comment]
thanks !
the weird thing is the feed input is not suppose to be so big, it suppose to be the height of two lines, just like the demo

https://sapui5.hana.ondemand.com/#/entity/sap.m.FeedInput/sample/sap.m.sample.Feed

any idea why is that ?

**Comment by oblomov-dev** [comment]
yes these ui5 controls sometimes behave really unexpected, have no idea, looks also fine to me. in the demo they put it directly under the xml view but is should work with the page in the similar way 🤷‍♂️  but i am sure any kind of container around it helps most of the times in this cases.

**Comment by choper725** [comment]
you were right, wrapping the feedinput in vbox did the trick, fixed with PR

**Pull request merged**
