### PR TITLE
status indicator demo

### PR DESCRIPTION
**Pull request by choper725**
demo 196

### CODE REVIEW

**Comment by oblomov-dev** [comment]
Thanks!

**Comment by oblomov-dev** [comment]
nice sample @choper725 
image

if you want, feel also free to add it to the overview, then it is easier to find for everyone. did it now with https://github.com/abap2UI5/abap2UI5-samples/pull/185
image

if we continue like this, maybe one day we have the whole UI5 Lib integrated 😅

**Comment by choper725** [comment]
i will add it.

dont know if you noticed, we have like 95% of the sdk in xml view.. :)

**Comment by oblomov-dev** [comment]
yes i tried to add as much samples as i found to the overview (but i am sure i missed some) and also tried to create somehow a understandable structure, but yes still work in progress, feel free to adjust and add.

ahh nice! yes 95% is a very good value :) we have nearly 200 samples now, great!

**Comment by choper725** [comment]
yes! we pretty much added most of the controls in the sdk..

**Pull request merged**
