### PR TITLE
demo 147

### PR DESCRIPTION
**Pull request by choper725**

### CODE REVIEW

**Comment by oblomov-dev** [comment]
image
image

**Comment by oblomov-dev** [comment]
@choper725 wow very cool stuff! thank you!

**Comment by choper725** [comment]
for now its static, i need to figure out how to integrate it with model binding somehow..
maybe from js, as this is a complex json..

can i add to the model directly from js.  ?

**Comment by oblomov-dev** [comment]
i always try to define a custom control and there you can use as attributes tables or other complex jsons. You can use the message manager custom control as an example. If you want to send other formats to the frontend, this should be also no problem as it is done with the tree table, you can also find a sample for this.

At the frontend i would redefine the setAttribute method of the custom control, to set the data form the backend into the Chart framework.

But to be honest, i did not take a look into the demos, so let me know what you exactly need.

**Comment by choper725** [comment]
hi @oblomov-dev  i could really need your help on this one,
im trying to make a CC for chartjs,
as per your suggestion im using Array type in the CC,
and for that to work i had to add compress to the bind logic in order to get the condensed json in the CC (without the empty abap values) i implemented it just like you added pretty_print in the bind methods.

now i got it to work, but when i try to update the model upon a change in abap i get a abap error,
image
image

**Comment by oblomov-dev** [comment]
ah ok, interesting error. 
can you send a PR with the actual version? how can i reproduce it? i can try to take a look to it in the next days.

**Comment by choper725** [comment]
created a PR #769
[chartjs cc demo.txt](https://github.com/abap2UI5/abap2UI5-samples/files/13906601/chartjs.cc.demo.txt)
this is the demo for it..

when i press update button in the top of the of the page i get the error,
i guess my cc is not complete but i dont really know how to advance when i get an abap error once trying to update..

**Comment by oblomov-dev** [comment]
ok i'll try to check this. Just out of curiosity, why do you use "compress" with the /ui2/json serialization?

**Comment by choper725** [comment]
because in the CC the recived config array is full of all the values from the defined atruc ty_chart,
and chartjs expect only strict values as it got internal defaults
the full json struc is around 150 values and in each table you use 20, maybe less

**Comment by oblomov-dev** [comment]
* added the txt to demo 148, its no problem when there are still bugs, its just the sample repository and this makes it easier to talk about
* nice, overlooked the compress function, to keep the requests smaller from my point of you it makes sense to activate it in general for every binded data, tested it here: https://github.com/abap2UI5/abap2UI5/tree/activate-compress-for-binding does this also work for you or do you see any problems in your apps?
* you work with a strcture and then have a table as an component, i think this nested structure is a use case i never had before, when i change the binding to one way binding, it works, updated the demo here: https://github.com/abap2UI5/abap2UI5-samples/blob/main/src/z2ui5_cl_demo_app_148.clas.abap

but yes i got the problem, just could check it quickly but i will try to find more time in the next days and check if there is a way to activate two way binding for nested structures/tables. thanks so far for your work!

**Comment by choper725** [comment]
> * added the txt to demo 148, its no problem when there are still bugs, its just the sample repository and this makes it easier to talk about
> * nice, overlooked the compress function, to keep the requests smaller from my point of you it makes sense to activate it in general for every binded data, tested it here: https://github.com/abap2UI5/abap2UI5/tree/activate-compress-for-binding does this also work for you or do you see any problems in your apps?
> * you work with a strcture and then have a table as an component, i think this nested structure is a use case i never had before, when i change the binding to one way binding, it works, updated the demo here: https://github.com/abap2UI5/abap2UI5-samples/blob/main/src/z2ui5_cl_demo_app_148.clas.abap
> 
> but yes i got the problem, just could check it quickly but i will try to find more time in the next days and check if there is a way to activate two way binding for nested structures/tables. thanks so far for your work!

* great !
* i need to pull again and run tests on default compress in the binds, i guess there would be problems if a value was declared in abap and was not set with a value , and later was used in a binding expression ... i know i used that once, just couldnt find where it was...
* the problem is that the array is a nested struc with tables and struc ??

**Comment by oblomov-dev** [comment]
Yes this use case was never done before, I am sure when you split the structure and send the tables as separated attributes to the fronted the two way binding would work. But anyway it makes sense to check if there is way that also the actual version works.

**Comment by oblomov-dev** [comment]
added now:
https://github.com/abap2UI5/abap2UI5/blob/e11cccf9ed575da7238ebb30805c0b69af9037ac/src/01/01/z2ui5_cl_fw_model.clas.abap#L85

demo 148 with two way binding works on my side.

but just made a quick and dirty change, so expect some bugs. you can test with the following branch:
https://github.com/abap2UI5/abap2UI5/tree/activate-compress-for-binding

Best regards.

**Comment by choper725** [comment]
pulled the activate-compress-for-binding branch and ran tests regarding to default compress binding, for now seems ok...
but i think it will be great if the compress will be default to true, but can be changable to false if indicated in the binding..

i see there is no dump for two way binding.. ill continue to work on the chartjs cc

**Comment by oblomov-dev** [comment]
(1) compress
ok great i will also do some more checks on my side and then push it to main.
(2) two way binding
👍

**Comment by choper725** [comment]
im getting an error in latest pull from this branch in my handler that check_debugging is missing from http_get method.

**Comment by oblomov-dev** [comment]
activated compress in general now, needed to adjust the index.html for this. my tests are succesfully.

yes i keep it as an optimal parameter that it can be manually deactivated. but in general i like to keep it simple and do not want to add too many parameters. maybe i will ask you in a few month ago and if you have no use case for this till then, i would delete it.

**Comment by choper725** [comment]
are you referring the check_debugging param ??

**Comment by oblomov-dev** [comment]
Ah no I mean the compress function.

**Comment by choper725** [comment]
ohh i figured that check debugging is removed as its now via shortcut so parameter is irrelevant,

any way, any pointers on how can i get model change event inside my CC ??
dont seem to get it to work..

image

tried all kind of things... nothing worked...

**Comment by oblomov-dev** [comment]
define a method setAttribute (e.g. setConfig), then the method is called automatically when binded data is changed and you can proceed your functionality.

**Comment by oblomov-dev** [comment]
just pulled all actual changes to main now. just create a new issue for further questions or errors.

**Pull request merged**
